[tool.poetry]
name = "enelvo-microservice"
version = "0.9.4"
description = "Enelvo pt_BR normalizer microservice."
authors = ["Thiago Carvalho D'√Åvila <thiagocavila@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/staticdev/enelvo-microservice"
repository = "https://github.com/staticdev/enelvo-microservice"

[tool.poetry.dependencies]
python = "^3.7"
grpcio = "^1.33.2"
protobuf = "^3.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
